name: Build and Deploy Fullstack App

on:
  push:
    branches:
      - main
    paths:
      - "fullstack-app/frontend/**"
      - "fullstack-app/backend/**"
      - "k8s/fullstack/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            meriemdevopsacr2026.azurecr.io \
            -u "${{ secrets.ACR_USERNAME }}" \
            --password-stdin

      - name: Build backend image
        run: |
          docker build \
            -t meriemdevopsacr2026.azurecr.io/fullstack-backend:${{ github.sha }} \
            -t meriemdevopsacr2026.azurecr.io/fullstack-backend:latest \
            ./fullstack-app/backend

      - name: Build frontend image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL="" \
            -t meriemdevopsacr2026.azurecr.io/fullstack-frontend:${{ github.sha }} \
            -t meriemdevopsacr2026.azurecr.io/fullstack-frontend:latest \
            ./fullstack-app/frontend

      - name: Scan backend with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            meriemdevopsacr2026.azurecr.io/fullstack-backend:${{ github.sha }}

      - name: Scan frontend with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            meriemdevopsacr2026.azurecr.io/fullstack-frontend:${{ github.sha }}

      - name: Push backend image
        run: |
          docker push meriemdevopsacr2026.azurecr.io/fullstack-backend:${{ github.sha }}
          docker push meriemdevopsacr2026.azurecr.io/fullstack-backend:latest

      - name: Push frontend image
        run: |
          docker push meriemdevopsacr2026.azurecr.io/fullstack-frontend:${{ github.sha }}
          docker push meriemdevopsacr2026.azurecr.io/fullstack-frontend:latest

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-devops-project \
            --name aks-devops \
            --overwrite-existing

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f k8s/fullstack/configmap.yml
          kubectl apply -f k8s/fullstack/postgres.yml
          kubectl apply -f k8s/fullstack/backend.yml
          kubectl apply -f k8s/fullstack/frontend.yml

      - name: Deploy SHA images
        run: |
          kubectl set image deployment/backend \
            backend=meriemdevopsacr2026.azurecr.io/fullstack-backend:${{ github.sha }}

          kubectl set image deployment/frontend \
            frontend=meriemdevopsacr2026.azurecr.io/fullstack-frontend:${{ github.sha }}

      - name: Wait for backend rollout
        run: |
          kubectl rollout status deployment/backend --timeout=180s

      - name: Wait for frontend rollout
        run: |
          kubectl rollout status deployment/frontend --timeout=180s
